name: Android

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assemble-release:
    name: Assemble Release APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up JDK 17 and Gradle
      uses: ./.github/actions/setup-java-gradle

    - name: Assemble APKs
      run: ./gradlew assembleDebug assemblePre_release assembleRelease

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: osudroid-apks
        path: "**/build/outputs/apk/**/*.apk"
